# Generated by Django 4.2.20 on 2025-04-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='New Workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshop.level'),
        ),
    ]
