# Generated by Django 4.2.20 on 2025-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_name_alter_workshop_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='New Workshop', max_length=50),
        ),
    ]
