# Generated by Django 4.2.20 on 2025-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.PositiveBigIntegerField(default=1, help_text='Please indicate number of participants'),
        ),
    ]
