# Generated by Django 4.2.20 on 2025-04-11 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_booking_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-appointment_date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
