# Generated by Django 4.2.20 on 2025-04-16 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_booking_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='excerpt',
            field=models.TextField(default='Default excerpt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(default=1, help_text='Please indicate number of participants up to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
