# Generated by Django 4.2.20 on 2025-04-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_workshop_excerpt_alter_booking_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['appointment_date']},
        ),
    ]
