# Generated by Django 4.2.20 on 2025-04-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='ContactRequest',
        ),
    ]
